# Generated by Django 2.2.7 on 2020-03-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
