# Generated by Django 2.2.7 on 2020-03-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_blog_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time'], 'verbose_name': '个人博客', 'verbose_name_plural': '个人博客'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='reading',
        ),
    ]
