# Generated by Django 2.2.7 on 2020-03-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200322_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='commentary',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Commentary'),
        ),
    ]
