# Generated by Django 2.2.7 on 2020-03-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200322_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='comment.Commentary'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment', to='comment.Commentary'),
        ),
    ]
